version: '2.1'
services:
  frontend:
    image: elastest/eds-frontend:latest
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 4000
      - 6065
      - 8000
    networks:
      - elastest_elastest

  memsipe:
    image: elastest/eds-memsipe:latest
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5050
    links:
      - frontend
    networks:
      - elastest_elastest

  zigbeeipe:
    image: elastest/eds-zigbeeipe:latest
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5001
    links:
      - frontend
    networks:
      - elastest_elastest

  rest_app:
    image: elastest/eds-api:latest
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 8080
      - 9090
    networks:
      - elastest_elastest

networks:
  elastest_elastest:
    external: true
